{
 "title": "Caddy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(caddy_http_requests_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (server, handler, code, method) (rate(caddy_http_request_duration_seconds_count{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server, handler, code, method) (caddy_http_request_duration_seconds_count{instance=\"$instance\", handler!=\"metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (server, handler, code, method) (rate(caddy_http_request_size_bytes_sum{instance=\"$instance\"}[5m])) / sum by (server, handler, code, method) (rate(caddy_http_request_size_bytes_count{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP response size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (server, handler, code, method) (rate(caddy_http_response_size_bytes_sum{instance=\"$instance\"}[5m])) / sum by (server, handler, code, method) (rate(caddy_http_response_size_bytes_count{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (server, handler, code, method) (rate(caddy_http_request_duration_seconds_sum{instance=\"$instance\"}[5m])) / sum by (server, handler, code, method) (rate(caddy_http_request_duration_seconds_count{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP response duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (server, handler, code, method) (rate(caddy_http_response_duration_seconds_sum{instance=\"$instance\"}[5m])) / sum by (server, handler, code, method) (rate(caddy_http_response_duration_seconds_count{instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}